server:
  image: itzg/minecraft-server:latest
  version: "1.21.11"
  mode: "survival"
  memory: "1G"
  onlineMode: "FALSE"
  type: "PAPER"

rcon:
  port: 25575
  password: "supersecretpassword"

service:
  nodePort: 30565

persistence:
  storageClass: standard
  size: 1Gi