prometheus:
  server:
    persistentVolume:
      enabled: false
  alertmanager:
    persistence:
      enabled: false
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: prometheus-self
          static_configs:
            - targets:
              - localhost:9090
        - job_name: minecraft
          static_configs:
            - targets:
              - minecraft-exporter.default.svc.cluster.local:9150

grafana:
  adminPassword: "admin"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus-MS
        type: prometheus
        url: http://monitoring-prometheus-server.monitoring.svc.cluster.local:80
        access: proxy
        isDefault: true